from building import * #scons
import os              #pythonos

cwd = GetCurrentDir()  # 
src = Glob('*.c')      #.c
CPPPATH = [cwd]        #

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)
#Applications srcC  

#
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
