import os
import rtconfig
from building import *

Import('SDK_LIB') # SDK_LIB 

cwd = GetCurrentDir() #

# add general drivers #
src = Split('''
board.c
''')

path =  [cwd]         #path

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

#Drivers board.c  
Return('group')
#
